# NumPy library

In [2]:
import numpy as np

## Lists

In [5]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.random.rand()

0.7622575472562606

In [14]:
np.random.rand(6)

array([0.03217328, 0.70875231, 0.16237884, 0.40129292, 0.9179872 ,
       0.82168331])

In [15]:
np.random.rand(3,3)

array([[0.13127105, 0.68211317, 0.88220145],
       [0.33354385, 0.22748251, 0.01508329],
       [0.14121596, 0.41624893, 0.40043167]])

In [16]:
np.random.randint(1,89)

13

In [17]:
np.random.randint(1,100,(5,5))

array([[34, 82, 42, 20,  3],
       [71, 80, 72,  2, 38],
       [23, 65, 63, 51, 16],
       [15, 30, 93,  3, 95],
       [29, 85, 94, 89, 62]])

## Shape y Reshape

In [21]:
arr = np.random.randint(1,20,(4,4))
arr

array([[10,  8, 10,  8],
       [ 5, 11, 17,  3],
       [ 1, 16, 10, 18],
       [15, 10,  8, 16]])

In [22]:
arr.shape

(4, 4)

In [25]:
arr.reshape(2,8)

array([[10,  8, 10,  8,  5, 11, 17,  3],
       [ 1, 16, 10, 18, 15, 10,  8, 16]])

In [26]:
arr.reshape(8,2)

array([[10,  8],
       [10,  8],
       [ 5, 11],
       [17,  3],
       [ 1, 16],
       [10, 18],
       [15, 10],
       [ 8, 16]])

In [27]:
np.reshape(arr,(2,8))

array([[10,  8, 10,  8,  5, 11, 17,  3],
       [ 1, 16, 10, 18, 15, 10,  8, 16]])

In [30]:
arr

array([[10,  8, 10,  8],
       [ 5, 11, 17,  3],
       [ 1, 16, 10, 18],
       [15, 10,  8, 16]])

### Reshape as C programing language (first rows then columns)

In [28]:
np.reshape(arr,(1,16),'C')

array([[10,  8, 10,  8,  5, 11, 17,  3,  1, 16, 10, 18, 15, 10,  8, 16]])

### Reshape as Fortran programingo language (first columns the rows)

In [29]:
np.reshape(arr,(1,16),'F')

array([[10,  5,  1, 15,  8, 11, 16, 10, 10, 17, 10,  8,  8,  3, 18, 16]])

### Reshape aleatory how is defined in my system


In [32]:
np.reshape(arr,(1,16),'A')

array([[10,  8, 10,  8,  5, 11, 17,  3,  1, 16, 10, 18, 15, 10,  8, 16]])