# NumPy library

In [85]:
import numpy as np

## Lists

In [86]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [88]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [89]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [90]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [91]:
np.random.rand()

0.9118169346527484

In [92]:
np.random.rand(6)

array([0.13456959, 0.09590726, 0.83791844, 0.86366174, 0.70714996,
       0.58985268])

In [93]:
np.random.rand(3,3)

array([[0.03153462, 0.80325959, 0.61653359],
       [0.77748966, 0.29047402, 0.98612677],
       [0.18411392, 0.09717344, 0.15229221]])

In [94]:
np.random.randint(1,89)

30

In [95]:
np.random.randint(1,100,(5,5))

array([[58, 22, 15, 24, 56],
       [35, 20, 61, 98, 92],
       [22, 59,  8, 64, 89],
       [39, 33, 61, 58, 70],
       [96, 11,  7, 31, 98]])

## Shape y Reshape

In [96]:
arr = np.random.randint(1,20,(4,4))
arr

array([[19, 19, 14, 13],
       [ 8, 12, 18, 15],
       [13, 15, 18,  3],
       [ 1, 10, 15, 15]])

In [97]:
arr.shape

(4, 4)

In [98]:
arr.reshape(2,8)

array([[19, 19, 14, 13,  8, 12, 18, 15],
       [13, 15, 18,  3,  1, 10, 15, 15]])

In [99]:
arr.reshape(8,2)

array([[19, 19],
       [14, 13],
       [ 8, 12],
       [18, 15],
       [13, 15],
       [18,  3],
       [ 1, 10],
       [15, 15]])

In [100]:
np.reshape(arr,(2,8))

array([[19, 19, 14, 13,  8, 12, 18, 15],
       [13, 15, 18,  3,  1, 10, 15, 15]])

In [101]:
arr

array([[19, 19, 14, 13],
       [ 8, 12, 18, 15],
       [13, 15, 18,  3],
       [ 1, 10, 15, 15]])

### Reshape as C programing language (first rows then columns)

In [102]:
np.reshape(arr,(1,16),'C')

array([[19, 19, 14, 13,  8, 12, 18, 15, 13, 15, 18,  3,  1, 10, 15, 15]])

### Reshape as Fortran programingo language (first columns the rows)

In [103]:
np.reshape(arr,(1,16),'F')

array([[19,  8, 13,  1, 19, 12, 15, 10, 14, 18, 18, 15, 13, 15,  3, 15]])

### Reshape aleatory how is defined in my system


In [104]:
np.reshape(arr,(1,16),'A')

array([[19, 19, 14, 13,  8, 12, 18, 15, 13, 15, 18,  3,  1, 10, 15, 15]])

## Most reelevant functions numpy

In [105]:
arr.max()

19

In [106]:
matrix = arr.reshape(4,4)
matrix

array([[19, 19, 14, 13],
       [ 8, 12, 18, 15],
       [13, 15, 18,  3],
       [ 1, 10, 15, 15]])

In [107]:
matrix.max(0)

array([19, 19, 18, 15])

In [108]:
matrix.max(1)

array([19, 18, 18, 15])

In [109]:
matrix.argmax()

0

In [110]:
matrix.argmax(0)

array([0, 0, 1, 1], dtype=int64)

In [111]:
matrix.argmax(1)

array([0, 2, 2, 2], dtype=int64)

Also exist `min()` and `argmin()` they have the same function

### Peak to peak

In [112]:
arr.ptp()

18

In [113]:
matrix.ptp(0)

array([18,  9,  4, 12])

In [114]:
matrix.ptp(1)

array([ 6, 10, 15, 14])

In [115]:
np.percentile(arr,50)

14.5

In [116]:
arr.sort()
arr

array([[13, 14, 19, 19],
       [ 8, 12, 15, 18],
       [ 3, 13, 15, 18],
       [ 1, 10, 15, 15]])

In [117]:
np.median(arr)

14.5

In [118]:
np.median(matrix,0)

array([ 5.5, 12.5, 15. , 18. ])

In [119]:
np.var(arr)

26.125

In [120]:
np.std(arr)

5.111262075065218

In [121]:
np.mean(arr)

13.0

In [122]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [123]:
a

array([[1, 2],
       [3, 4]])

In [134]:
b.shape

(2,)

In [132]:
np.expand_dims(b, axis=0).shape

(1, 2)

In [133]:

np.expand_dims(b, axis=1).shape

(2, 1)

In [127]:
np.concatenate((a,np.expand_dims(b, axis = 0)), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [128]:
b.T

array([5, 6])

In [129]:
np.concatenate((a,np.expand_dims(b, axis = 0).T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

## Copy

In [143]:
arr = np.arange(0,21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

Here `s_arr` is defined as a slice of `arr` if we modify `s_arr` it will also modify `arr` cause `s_arr` is defined with reference like pointers in C if we want to avoid that we should define `s_arr` as copy

In [144]:
s_arr = arr[0:11]
s_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [145]:
s_arr *= 7
s_arr

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [146]:
arr

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

To prevent this from happen we use the methood `.copy()`

In [148]:
arr_copy = arr.copy()
arr

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [149]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100])

In [150]:
arr

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

## Conditions

In [153]:
arr = np.random.randint(0, 100, 15)
arr

array([10, 92, 92, 14, 44, 27, 93,  3,  9, 54, 99, 89, 68, 36, 19])

In [156]:
greater_t_50 = arr > 50
greater_t_50

array([False,  True,  True, False, False, False,  True, False, False,
        True,  True,  True,  True, False, False])

In [157]:
arr[greater_t_50]

array([92, 92, 93, 54, 99, 89, 68])

Same as:

In [158]:
arr[(arr > 50)]

array([92, 92, 93, 54, 99, 89, 68])

Also can set value

In [166]:
arr[(arr > 25) & (arr < 75)] = 0
arr

array([10, 92, 92, 14,  0,  0, 93,  3,  9,  0, 99, 89,  0,  0, 19])

## Operations

In [172]:
arr =  np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [173]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [174]:
1 / arr

C:\Users\mario\AppData\Local\Temp\ipykernel_23204\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [175]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Matrix multiplication

In [177]:
A = np.random.randint(0, 10, 6).reshape(3,2)
B = np.random.randint(0, 10, 6).reshape(2,3)
print(A)
print(B)

[[3 2]
 [0 3]
 [9 3]]
[[7 4 4]
 [7 1 7]]


In [178]:
np.matmul(A, B)

array([[35, 14, 26],
       [21,  3, 21],
       [84, 39, 57]])

In [179]:
A @ B

array([[35, 14, 26],
       [21,  3, 21],
       [84, 39, 57]])